export default [
    {
        id: 1,
        name: "Стол офисный угловой",
        image: "",
        select: {},
        amount: 1,
        price: 8711,
    },
    {
        id: 2,
        name: "Стол офисный угловой",
        image: "",
        select: {},
        amount: 1,
        price: 12,
    },
    {
        id: 3,
        name: "Стол офисный угловой",
        image: "",
        select: {},
        amount: 1,
        price: 12,
    },
    {
        id: 4,
        name: "Стол офисный угловой",
        image: "",
        select: {},
        amount: 1,
        price: 12,
    },
    {
        id: 5,
        name: "Стол офисный угловой",
        image: "",
        select: {},
        amount: 1,
        price: 12,
    },
    {
        id: 6,
        name: "Стол офисный угловой",
        image: "",
        select: {},
        amount: 1,
        price: 12,
    },
    {
        id: 7,
        name: "Стол офисный угловой",
        image: "",
        select: {},
        amount: 1,
        price: 12,
    }
]